

runtime: nodejs20
default_expiration: "0d 0h 0m 10s"

instance_class: B4

basic_scaling:
  max_instances: 2
  idle_timeout: 40m



# handlers:
#   - url: /
#     static_dir: static_dist
#
#   - url: /.*
#     script: auto

